import { Lead, Presupuesto, InformeEntrega, SurveyResponse } from '@/types/crm';

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead-1',
    name: 'Carlos Mendoza',
    company: 'C.M.H Motors',
    email: 'contacto@cmhmotors.cl',
    phone: '+56 9 8412 9011',
    stage: 'nuevo',
    origin: 'meta_ads',
    value: 850000,
    serviceInterest: 'Sitio Web Pro + Catálogo de Vehículos con WhatsApp',
    notes: 'Interesado en subir inventario de 35 autos seminuevos. Requiere buscador por marca y año.',
    createdAt: '2026-08-10',
    lastActivity: 'Hace 2 horas (Meta Lead Form)',
  },
  {
    id: 'lead-2',
    name: 'Paulina Ricci',
    company: 'Pali Rucci',
    email: 'ventas@palirucci.cl',
    phone: '+56 9 7654 3210',
    stage: 'conversacion',
    origin: 'web_form',
    value: 620000,
    serviceInterest: 'Rediseño Ecommerce Vestuario / Web Pro',
    notes: 'Tienda actual en Shopify lenta. Busca migración a catálogo rápido con Webpay Plus directo.',
    createdAt: '2026-08-08',
    lastActivity: 'Ayer (Llamada telefónica realizada)',
  },
  {
    id: 'lead-3',
    name: 'Dra. María José Altamirano',
    company: 'Altavita Salud',
    email: 'gerencia@altavitasalud.cl',
    phone: '+56 9 5543 2198',
    stage: 'cotizado',
    origin: 'whatsapp',
    value: 1200000,
    serviceInterest: 'Plataforma Web + Sistema Reserva de Horas Médicas',
    notes: 'Se envió PPTO N° 227. Pendiente aprobación de directorio este viernes.',
    createdAt: '2026-08-05',
    lastActivity: 'Cotización N° 227 enviada por WhatsApp',
  },
  {
    id: 'lead-4',
    name: 'Gonzalo Morales',
    company: 'Refugio Noche Andina',
    email: 'reservas@nocheandina.cl',
    phone: '+56 9 4432 1098',
    stage: 'cerrado',
    origin: 'meta_ads',
    value: 490000,
    serviceInterest: 'Landing Page Reserva de Cabañas en Elqui',
    notes: '¡Contrato firmado! Proyecto iniciado con anticipo del 50% recibido en Scotiabank.',
    createdAt: '2026-08-01',
    lastActivity: 'En desarrollo (Anticipo 50% abonado)',
  },
  {
    id: 'lead-5',
    name: 'Fernando Tamariz',
    company: 'Tamar Propiedades',
    email: 'ftamar@tamarpropiedades.cl',
    phone: '+56 9 9876 5432',
    stage: 'perdido',
    origin: 'web_form',
    value: 950000,
    serviceInterest: 'Portal Inmobiliario con Integración Portalinmobiliario',
    notes: 'Postergaron inversión para el Q4 por reestructuración interna.',
    createdAt: '2026-07-28',
    lastActivity: 'Cierre de seguimiento (Sin presupuesto activo)',
  },
];

export const INITIAL_PRESUPUESTOS: Presupuesto[] = [
  {
    id: 'ppto-228',
    correlativo: 228,
    clientName: 'Dra. María José Altamirano',
    clientCompany: 'Altavita Salud SpA',
    clientRut: '77.291.803-K',
    clientEmail: 'gerencia@altavitasalud.cl',
    clientPhone: '+56 9 5543 2198',
    date: '2026-08-12',
    validityDays: 15,
    items: [
      {
        id: 'item-1',
        title: 'Desarrollo Web Pro Corporativo + Catálogo Médico',
        description: 'Maquetación UX/UI responsiva, diseño exclusivo en Next.js/Tailwind, optimización SEO local y velocidad Ultra-Fast.',
        netAmount: 750000,
      },
      {
        id: 'item-2',
        title: 'Módulo Integrado de Agenda y Reserva de Horas',
        description: 'Calendario interactivo con confirmación por e-mail, envío de recordatorios y formulario de pre-fichas clínicas.',
        netAmount: 450000,
      },
      {
        id: 'item-3',
        title: 'Configuración de Correos Corporativos + SSL Dedicado',
        description: 'Alta de 5 casillas de correo profesional (ej: contacto@altavitasalud.cl) con certificado de seguridad SSL gratis vitalicio.',
        netAmount: 0,
      },
    ],
    appliesIva: true,
    notes: 'Condiciones de pago: 50% al inicio del proyecto y 50% contra entrega conforme y publicación en dominio definitivo.',
    totalNet: 1200000,
    ivaAmount: 228000,
    totalAmount: 1428000,
    anticipo50: 714000,
    nicChileFee: 9990,
    status: 'enviado',
  },
  {
    id: 'ppto-227',
    correlativo: 227,
    clientName: 'Gonzalo Morales',
    clientCompany: 'Refugio Noche Andina',
    clientRut: '76.882.110-4',
    clientEmail: 'reservas@nocheandina.cl',
    clientPhone: '+56 9 4432 1098',
    date: '2026-08-02',
    validityDays: 15,
    items: [
      {
        id: 'item-10',
        title: 'Landing Page de Alto Impacto para Cabañas Elqui',
        description: 'Galería fotográfica HD, mapa interactivo, botón directo a WhatsApp reservas y módulo de tarifas por temporada.',
        netAmount: 490000,
      },
    ],
    appliesIva: true,
    notes: 'Incluye 90 días de garantía técnica post-entrega y soporte prioritario.',
    totalNet: 490000,
    ivaAmount: 93100,
    totalAmount: 583100,
    anticipo50: 291550,
    nicChileFee: 9990,
    status: 'aceptado',
  },
];

export const INITIAL_INFORMES: InformeEntrega[] = [
  {
    id: 'inf-101',
    clientName: 'Gonzalo Morales',
    companyName: 'Refugio Noche Andina',
    clientRut: '76.882.110-4',
    webUrl: 'https://nocheandina.cl',
    deliveryDate: '2026-08-10',
    warrantyStartDate: '2026-08-10',
    warrantyEndDate: '2026-11-08',
    credentials: [
      { id: 'c1', title: 'Administrador CMS / Panel Web', url: 'https://nocheandina.cl/admin', username: 'admin_nocheandina', passHint: 'Enviada por canal privado seguro' },
      { id: 'c2', title: 'Hosting & Servidor Cloud Vango', url: 'https://cloud.vango.cl', username: 'nocheandina_host', passHint: 'Gestionado por PáginasPro' },
      { id: 'c3', title: 'Certificado de Seguridad SSL', url: 'https://nocheandina.cl', username: 'Let\'s Encrypt SSL', passHint: 'Renovación automática' },
    ],
    corporateEmails: [
      'reservas@nocheandina.cl',
      'contacto@nocheandina.cl',
      'gonzalo@nocheandina.cl',
    ],
    deliverablesChecklist: [
      { id: 'd1', label: 'Certificado de Seguridad SSL HTTPS Activo', completed: true },
      { id: 'd2', label: 'Diseño 100% Responsivo en Celulares y Tablets', completed: true },
      { id: 'd3', label: 'Integración de Formulario WhatsApp y Botones Directos', completed: true },
      { id: 'd4', label: 'Optimización SEO Técnico Google Search Console', completed: true },
      { id: 'd5', label: 'Casillas de Correo Corporativo Pruebas Recibidas y Enviadas', completed: true },
      { id: 'd6', label: 'Capacitación en Video para Administración de Contenidos', completed: true },
    ],
    notes: 'El cliente confirma recepción conforme de todas las credenciales y casillas de correo configuradas.',
  },
];

export const INITIAL_SURVEYS: SurveyResponse[] = [
  {
    id: 'srv-1',
    clientName: 'Gonzalo Morales',
    companyName: 'Refugio Noche Andina',
    overallRating: 5,
    usabilityRating: 5,
    attentionRating: 5,
    npsScore: 10,
    comments: 'Excelente trabajo de Diego y el equipo de PáginasPro.cl. La web quedó súper rápida y ya empezamos a recibir reservas por WhatsApp.',
    createdAt: '2026-08-11',
    verified: true,
  },
  {
    id: 'srv-2',
    clientName: 'Rodrigo Fuentes',
    companyName: 'Transportes Norte Chico',
    overallRating: 5,
    usabilityRating: 4,
    attentionRating: 5,
    npsScore: 9,
    comments: 'Muy profesional la entrega del informe con las claves y los 90 días de garantía. Da mucha tranquilidad.',
    createdAt: '2026-07-29',
    verified: true,
  },
  {
    id: 'srv-3',
    clientName: 'Camila Reyes',
    companyName: 'Estudio Jurídico Reyes & Asoc.',
    overallRating: 4,
    usabilityRating: 5,
    attentionRating: 5,
    npsScore: 9,
    comments: 'Cumplieron exactamente con los plazos prometidos. La cotización clara con IVA y los datos de Scotiabank facilito todo el proceso.',
    createdAt: '2026-07-15',
    verified: true,
  },
];
